# Generated by Django 5.0.6 on 2024-06-07 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.TextField(default=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
