# Generated by Django 5.0.6 on 2024-05-29 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='read_books',
            field=models.ManyToManyField(blank=True, related_name='reader', to='books.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='uploaded_books',
            field=models.ManyToManyField(blank=True, related_name='uploader', to='books.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.ManyToManyField(blank=True, related_name='user_notification', to='accounts.notification'),
        ),
    ]
